### PR TITLE
Introduce the uid property

### PR DESCRIPTION
**Pull request by tcitworld**
Bases itself on #12

### CODE REVIEW

**Comment by fazibear** [comment]
Same here :)

BTW codeclimate complains about functions complexity, we should take care about it.

**Comment by tcitworld** [comment]
Rebased.

**Comment by tcitworld** [comment]
Yes, I noticed after https://github.com/fazibear/ex_ical/pull/14 that the recurrence rules could be quite improved.

**Comment by tcitworld** [comment]
And rebased again.

**Comment by fazibear** [comment]
Great!
Do you have any other changes or should I make a release?

**Comment by tcitworld** [comment]
Not until next week ;)

**Pull request merged**
