### PR TITLE
Parse valid datetimes

### LINKED ISSUE #6: Not all valid iCalendar Date/Date-Time formats can be parsed
### Current Behavior

Some of the valid date/date-time formats (as defined in [RFC 2445](http://www.ietf.org/rfc/rfc2445.txt)) are not parsable.
For example, when trying to parse a `DTSTART` using a datetime with the local timezone:

``` bash
iex> ical = """
            BEGIN:VEVENT
            DTSTART:19690620T201804
            END:VEVENT
            """ # local time
iex> ExIcal.parse ical
** (FunctionClauseError) no function clause matching in ExIcal.DateParser.parse/2
    (ex_ical) lib/ex_ical/date_parser.ex:7: ExIcal.DateParser.parse("19690620T201804", nil)
    (ex_ical) lib/ex_ical/parser.ex:15: ExIcal.Parser.parse_line/2
     (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_ical) lib/ex_ical/parser.ex:8: ExIcal.Parser.parse/1
```

From what I can tell, Form 1 and Form 3 (below) are not currently handled.
### Expected Behavior

I'd expect all formats defined in the specs to be parsable by this library.
There are four valid input forms:
- **Form 1:** [Date-Time with local time (`19690620T201804`)](http://www.kanzaki.com/docs/ical/dateTime.html)
- **Form 2:** [Date-Time with UTC time (`19690620T201804Z`)](http://www.kanzaki.com/docs/ical/dateTime.html)
- **Form 3:** [Date-Time with local time + time zone reference (`TZID=America/Chicago:19690620T201804`)](http://www.kanzaki.com/docs/ical/dateTime.html)
- **Form 4:** [Date (`19690620`)](http://www.kanzaki.com/docs/ical/date.html)

Also, these inline time zones need to interact in a reasonable way with the global calendar time zones–inline time zones (Forms 2 & 3) should take precedence over global zones.

Here are some possible rules:

| # | Example Line | When no global `TZID` is set | When `TZID:Europe/Berlin` |
| --- | --- | --- | --- |
| 1 | `DTSTART:19690620` | No timezone (date) | No timezone (date) |
| 2* | `DTSTART:19690620Z` | No timezone (date) | No timezone (date) |
| 3 | `DTSTART:19690620T201804` | No timezone (local) | `Europe/Berlin` |
| 4 | `DTSTART:19690620T201804Z` | `UTD` | `UTD` (priority to zulu time marker) |
| 5 | `DTSTART;TZID=America/New_York:19690620T201804` | `America/New_York` | `America/New_York` (priority to inline tzid) |
| 6* | `DTSTART;TZID=America/New_York:19690620T201804Z` | `UDT` (priority to zulu time marker) | `UDT` (priority to zulu time marker) |

*_L2 & L6 are not in the spec, but I included them here for error tolerance_
### System Information
- **ExIcal:** observed on 0.0.3
- **Elixir:** 1.3.2
- **Erlang/OTP:** 19
- **OS:** Mac OS X 10.11.5

### PR DESCRIPTION
**Pull request by leesharma**
Resolves #6
### Major Changes
- **All valid combinations of `TZID:<global_tzid>` and inputted datestrings are now handled.** The following table is from `test/ex_ical_date_format_test.ex`. It shows the input formats and expected output both without the calendar-wide `TZID` property and when `TZID:America/Chicago`:
  
  ``` elixir
  [
  #---------------------------------------------+---------------+----------------------------------+
  #                               DTSTART input |   Parsed Date |  Timezone with Global TZID = ?   |
  #                                             |               |            nil | America/Chicago |
  #---------------------------------------------+---------------+----------------+-----------------+
  {                           "DTSTART:19690620",     date_match,  local_tzmatch,   local_tzmatch,},
  {                          "DTSTART:19690620Z",     date_match,    utc_tzmatch,     utc_tzmatch,},
  {                    "DTSTART:19690620T201804", datetime_match,  local_tzmatch, chicago_tzmatch,},
  {                   "DTSTART:19690620T201804Z", datetime_match,    utc_tzmatch,     utc_tzmatch,},
  { "DTSTART;TZID=Europe/Berlin:19690620T201804", datetime_match, berlin_tzmatch,  berlin_tzmatch,},
  {"DTSTART;TZID=Europe/Berlin:19690620T201804Z", datetime_match,    utc_tzmatch,     utc_tzmatch,},
  ]
  ```
- Add documentation (`@moduledoc` and `@doc`) to `ExIcal.DateParser`
- Add basic test files (with `doctest`) for all app modules
- Misc. refactoring and bugfixes
### Questions/Decisions
- As it is, the library can parse several formats that are invalid by the iCal spec:
  - `DTSTART:<YYYYMMDD>Z`
  - `DTSTART;TZID=<tzid>:<YYYYMMDD>Z`
  - `DTSTART;TZID=<tzid>:<YYYYMMDD>T<HHMMSS>Z`
  
  I think we treat these cases in reasonable ways, and that by handling them, we make the library more flexible. Maybe we should stay with the spec though? Thoughts?
- Since `%Timex.DateTime{}` can't handle floating dates (especially if we're sorting through them by range), we can't parse `<YYYYMMDD>T<HHMMSS>`-formatted dates ([Form 1](http://www.kanzaki.com/docs/ical/dateTime.html) by the docs) without a timezone. At the moment, I have them parse to `:local` time. It makes sense for some applications, but it may be a problem if the app using `ExIcal` is in a different timezone than the user.
  
  We may prefer to use `:utc` (the default for `%Timex.DateTime{}`. We may also want to add some sort of indicator (a `floating: true` property on the struct, for example) that it was imported as a floating local datetime. So, `:local` or `:utc`? Is an indicator of floating local dates worth it?

### CODE REVIEW

**Comment by leesharma** [comment]
Actually, I think `:utc` makes more sense than `:local`. That takes all ambiguity out of user versus server locations and will lead to more expected behavior. I'll update that in the code.

**Comment by fazibear** [comment]
Thank you for this great PR.

**Comment by leesharma** [comment]
Sure thing! I've got a bit of a selfish motivation–I want to use an iCal parsing package in my project, so I'd love to see this hit 1.0! :smile:

What are your other feature goals before reaching v1.0?

**Comment by fazibear** [comment]
BTW Just added credo to project, and automatic PR analysis. It will be nice to fix credo warrnings also. Thanks once again.

**Pull request merged**
